# Generated by Django 4.1.5 on 2023-01-27 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='stock',
        ),
    ]
